### ISSUE TITLE
/usr/bin/env: ‘jq -Mf’: No such file or directory

### ISSUE THREAD

**Issue by tmor** [knoguchi/grafana-dash#2]
## Summary

On Linux, `/usr/bin/env command` with `-option` will not work.

## Environments

- Ubuntu 18.04 LTS on WSL1

## Steps to reproduce

```shell
./update-datasource.jq --arg old "old datasource name" --arg new "new datasource name" < my_dashboard.json > edited_my_dashboard.json
...
/usr/bin/env: ‘jq -Mf’: No such file or directory
```

## Workaround

```shell
jq -Mf update-datasource.jq  ...
```

**Comment by knoguchi** [comment]
It's not env but the older jq that doesn't take -Mf option.  I will modify the README so it works for older jq.

**Comment by tmor** [comment]
> It's not env but the older jq that doesn't take -Mf option. I will modify the README so it works for older jq.

I'm using `jq-1.6` .
macOS is BSD-based, shebang supports multiple options. However, Linux does not support it.

please see here:  [いまさら聞けない、#! で始まる１行目の名前とenv指定時の挙動 - 基本へ帰ろう](https://japanrock-pg.hatenablog.com/entry/20100319/1268968887)

**Comment by knoguchi** [comment]
ah.  you are right.  env -S would do if your Linux uses GNU coreutils v8.30 or newer.

**Comment by knoguchi** [comment]
Fixed the readme and the script.
